### ISSUE TITLE
Yggdra Union PTX files

### ISSUE THREAD

**Issue by avibodek** [Raijinili/stingfiles#1]
Hi, do you have any idea how to view the CGs from Yggdra Union? I've been looking for a while to figure out how to convert the PTX files. There apparently was a PTX to TGA converter, but the link is dead and the creator is nowhere to be found.

**Comment by Raijinili** [comment]
The following should work if you have the `pt_image.py` file (and its requirements) from this repo.
```
from pt_image import PTXImage
PTXImage(pathToMyFile).toImage().save(someImageFilename)
```

The Pillow (image library) determines the image format from the [`save`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) parameter's file extension.

**Comment by quizerno** [comment]
Thank you. Ran into some issues though. 

Here's what I tried. 

```
from pt_image import PTXImage

pathToMyFile ="00000158.ptx"
someImageFilename = "1"
PTXImage(pathToMyFile).toImage().save(someImageFilename)
```


resulted in


> Traceback (most recent call last):
>   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 1987, in save
>     format = EXTENSION[ext]
> KeyError: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Game Archival\Games\YggdraUSA\PTX\converter.py", line 7, in <module>
>     PTXImage(pathToMyFile).toImage().save(someImageFilename)
>   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 1989, in save
>     raise ValueError('unknown file extension: {}'.format(ext))
> ValueError: unknown file extension: 
> 

Adding a file extension to the output name DOES get a file, but it's always a straight black line. It's possible I didn't install the imageio package correctly.

**Comment by Raijinili** [comment]
PIL needs a filename extension to figure out the type of image file you want. For example, if it sees .png, it saves as PNG format, which has a different internal format than GIF.

That's odd. It shouldn't work at all. 0158 is a file that starts with `@CNS`, which seems to be an archive file. I'm getting header assertion errors, even if I start the read at 0x21 (where the PTX header is). I need to investigate this sample, because the format doesn't seem to fit my understanding of PTX files.

**Comment by quizerno** [comment]
Are you sure you're not mistaking it for a different file? Since it appears to start with `@PTX` for me
![image](https://user-images.githubusercontent.com/43489654/60775350-e28c8a80-a0ef-11e9-8dba-f438bfae1dd1.png)

If you want I can send you the file. I'm not sure where the CGs are stored. I did manage to determine all of the card files (incidentally 00000158.ptx is the Ace Guard card graphic)

![image](https://user-images.githubusercontent.com/43489654/60775398-a7d72200-a0f0-11e9-9c95-525c4e8a9f2e.png)

**Comment by Raijinili** [comment]
That's very curious. My 0158 (in `/PSP_GAME/USRDIR/Data/data01.afs`) is named "btlc". Ace Guard's image is 0712, named "Card_3".
![0712-Card_3](https://user-images.githubusercontent.com/2422807/60778129-b844c800-a103-11e9-9e92-9f6f51080165.png)

Is that the GBA version? What did you use to extract that?

**Comment by quizerno** [comment]
This is the PSP version. I extracted it using QuickBMS with the .ASF script
https://aluigi.altervista.org/quickbms.htm
https://aluigi.altervista.org/bms/afs.bms

Are you saying that I can just directly grab it from the .asf archive? I can try it soon.

**Comment by Raijinili** [comment]
I modified and recompiled [PuyoTools](https://github.com/Raijinili/puyotools) to extract them in NUMBER-FILENAME (e.g. 0158-btlc) filename format.

Ah, your numbering is in hex. I chose not to use hex filenames, since Windows sorts them weirdly. Your 00000158 is my 0344. I need to look at that.

Edit: My library seems to work fine with 0344.
![0344](https://user-images.githubusercontent.com/2422807/60784369-a6bbea00-a11c-11e9-84ed-ca2e334c6148.png)

The output PNG is identical with the PNG from 0712, despite 0712 being a PTG file (which stores the data more efficiently by not storing blank rectangles).
